#!/system/bin/sh
export PATH=${PATH}:/system/bin:/system/xbin
chmod 777 /system/etc/init.d/*
logwrapper busybox run-parts /system/etc/init.d/ # We shouldn't prefer in-kernel busybox, as it may be outdated, etc.
